# Generated by Django 4.2.8 on 2023-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fadmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_arr', models.DateField(auto_now_add=True)),
                ('num_env', models.CharField(max_length=10)),
                ('num_rapp_pj', models.CharField(max_length=10)),
                ('pj', models.CharField(max_length=20)),
                ('num_rapp_pp', models.CharField(max_length=10)),
                ('num_plaint', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=100)),
                ('search_indice', models.IntegerField()),
            ],
        ),
    ]
