# Generated by Django 4.2.8 on 2023-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fadmin',
            name='date_arr',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ التوصل'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_env',
            field=models.CharField(max_length=10, verbose_name='رقم الارسال'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_plaint',
            field=models.CharField(max_length=10, verbose_name='رقم الشكاية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pj',
            field=models.CharField(max_length=1, verbose_name='رقم محضر الضابطة القضائية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pp',
            field=models.CharField(max_length=10, verbose_name='رقم محضر النيابة العامة'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='pj',
            field=models.CharField(max_length=20, verbose_name='الضابطة القضائية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='search_indice',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد مرات البحث'),
        ),
    ]
