# Generated by Django 4.0.3 on 2023-12-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_pj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pj', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type_rapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=20, unique=True, verbose_name='رمز المحضر')),
                ('nom_typerapp', models.CharField(max_length=20, verbose_name='رمز المحضر')),
            ],
        ),
        migrations.RemoveField(
            model_name='fadmin',
            name='pj',
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='date_arr',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ التوصل'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_env',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الارسال'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_plaint',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الشكاية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم محضر الضابطة القضائية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم محضر النيابة العامة'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='search_indice',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد مرات البحث'),
        ),
        migrations.CreateModel(
            name='Pjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadmin.type_pj')),
            ],
        ),
        migrations.AddField(
            model_name='fadmin',
            name='type_pj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fadmins', to='fadmin.pjs', verbose_name='الضابطة القضائية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fadmin',
            name='type_rapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rapp_type', to='fadmin.type_rapp', verbose_name='نوع المحضر'),
            preserve_default=False,
        ),
    ]
