# Generated by Django 4.2.8 on 2023-12-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0002_alter_fadmin_date_arr_alter_fadmin_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fadmin',
            name='num_env',
            field=models.CharField(max_length=20, verbose_name='رقم الارسال'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_plaint',
            field=models.CharField(max_length=20, verbose_name='رقم الشكاية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pj',
            field=models.CharField(max_length=20, verbose_name='رقم محضر الضابطة القضائية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pp',
            field=models.CharField(max_length=20, verbose_name='رقم محضر النيابة العامة'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='pj',
            field=models.CharField(max_length=30, verbose_name='الضابطة القضائية'),
        ),
    ]
