# Generated by Django 4.0.3 on 2024-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0002_type_pj_type_rapp_remove_fadmin_pj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fadmin',
            name='num_env',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الارسال'),
        ),
    ]
