# Generated by Django 4.0.3 on 2024-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0003_alter_fadmin_num_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjs',
            name='indice',
            field=models.CharField(max_length=3),
        ),
    ]
