# Generated by Django 4.2.8 on 2023-12-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0003_alter_fadmin_num_env_alter_fadmin_num_plaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_pj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=3)),
                ('pj', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='fadmin',
            name='id',
        ),
        migrations.CreateModel(
            name='Pjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadmin.type_pj')),
            ],
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='pj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fadmin.pjs', verbose_name='الضابطة القضائية'),
        ),
    ]
