# Generated by Django 4.2.8 on 2023-12-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0004_type_pj_remove_fadmin_id_pjs_alter_fadmin_pj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pjs',
            name='reporter',
        ),
    ]
