# Generated by Django 4.2.8 on 2023-12-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0005_remove_pjs_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pjs',
            old_name='p',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type_pj',
            old_name='pj',
            new_name='name_pj',
        ),
        migrations.AddField(
            model_name='pjs',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fadmin.type_pj'),
            preserve_default=False,
        ),
    ]
