# Generated by Django 4.0.3 on 2023-12-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0007_remove_type_pj_indice_pjs_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fadmin',
            name='type_pj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fadmin.type_pj', verbose_name='الضابطة القضائية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_env',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الارسال'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_plaint',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الشكاية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم محضر الضابطة القضائية'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='num_rapp_pp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم محضر النيابة العامة'),
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='pj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fadmin.pjs', verbose_name='نوع الضابطة القضائية'),
        ),
    ]
