# Generated by Django 4.0.3 on 2023-12-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0008_fadmin_type_pj_alter_fadmin_num_env_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fadmin',
            name='type_pj',
        ),
        migrations.AlterField(
            model_name='fadmin',
            name='pj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fadmin.type_pj', verbose_name='نوع الضابطة القضائية'),
        ),
    ]
