# Generated by Django 4.0.3 on 2023-12-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0009_remove_fadmin_type_pj_alter_fadmin_pj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fadmin',
            name='pj',
        ),
        migrations.AddField(
            model_name='fadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fadmin',
            name='type_pj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fadmin.pjs', verbose_name='الضابطة القضائية'),
            preserve_default=False,
        ),
    ]
