# Generated by Django 4.0.3 on 2023-12-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0010_remove_fadmin_pj_fadmin_id_fadmin_type_pj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fadmin',
            name='type_pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fadmins', to='fadmin.pjs', verbose_name='الضابطة القضائية'),
        ),
    ]
