# Generated by Django 4.0.3 on 2023-12-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadmin', '0011_alter_fadmin_type_pj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_rapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=20, verbose_name='رمز المحضر')),
                ('nom_typerapp', models.CharField(max_length=20, verbose_name='رمز المحضر')),
            ],
        ),
        migrations.AddField(
            model_name='fadmin',
            name='type_rapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rapp_type', to='fadmin.type_rapp', verbose_name='نوع المحضر'),
            preserve_default=False,
        ),
    ]
